### ISSUE TITLE
Unzip Errors

### ISSUE THREAD

**Issue by Notyouagain** [tailorvj/fullpagedashboard-client#3]
I am getting corrupt archive errors when I try to extract the img file.

**Comment by tailorvj** [comment]
From within the zip file?

Kind regards,
Tailor VJ

**Comment by Notyouagain** [comment]
Yes sir, I downloaded the zip file and have attempted several methods of extracting it (Winzip, WinRar, Windows File Explorer).  Basically the same process I have used for FPOS; download, extract the image, write the MicroSD, edit txt files before inserting in the Pi.  This one give me an error while trying to extract the img file from the zip file.  I have downloaded it twice and tried several methods to extract.

**Comment by tailorvj** [comment]
I've tested and the archive is good. Many other users have used it and it works for them. 

Just to make sure we are on the same page, you have downloaded the Experimental 0.2.0 release, yes?

Please try to download again and unzip on another machine. 

Here is a [direct link to the download](https://github.com/tailorvj/fullpagedashboard-client/releases/download/0.2.0-experimental/20190301-fullpageos-0.2.0-experimental-release.img.zip)
This is the [release page for FullPageDashboard-client 0.2.0](https://github.com/tailorvj/fullpagedashboard-client/releases/tag/0.2.0-experimental).

I'm closing this issue. 
Cheers,
Tailor

**Comment by Notyouagain** [comment]
I was able to get it to unzip with 7zip
